version: 2

report_sizes: true

builds:
  - id: build-x86_64
    builder: zig
    binary: skg
    targets: [x86_64-linux-gnu]
    flags:
      - -Doptimize=ReleaseFast

  - id: build-arm64
    builder: zig
    binary: skg
    targets: [aarch64-linux-gnu]
    flags:
      - -Doptimize=ReleaseFast

  - id: build-riscv64
    builder: zig
    binary: skg
    targets: [riscv64-linux-gnu]
    flags:
      - -Doptimize=ReleaseFast

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end -}}
      _linux
      {{- if index . "Abi" }}_{{ .Abi }}{{ end -}}
    formats: ["tar.gz"]
    builds_info:
      group: root
      owner: root

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: packages
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/tenebrux/skg
    description: "SKG - Static Key Group config language tools"
    maintainer: "Levi Smith <levi@tenebrux.com>"
    license: MIT
    vendor: tenebrux
    bindir: /usr/bin
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Build process updates"
      regexp: '^.*?(build|ci)(\(.+\))??!?:.+$'
      order: 300
    - title: Other work
      order: 9999

release:
  name_template: "v{{ .Version }}"
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/tenebrux/skg/compare/{{ .PreviousTag }}...{{ .Tag }}
