#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 6

enum {
  sym_identifier = 1,
  anon_sym_AT = 2,
  anon_sym_delete = 3,
  anon_sym_replace = 4,
  anon_sym_import = 5,
  anon_sym_LBRACK = 6,
  anon_sym_COMMA = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  sym_multiline_string = 12,
  sym_string = 13,
  sym_float = 14,
  sym_integer = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  sym_null = 18,
  sym_comment = 19,
  sym_document = 20,
  sym__statement = 21,
  sym_overlay_operation = 22,
  sym_import = 23,
  sym_block = 24,
  sym_block_array = 25,
  sym_block_array_item = 26,
  sym_scalar_array_field = 27,
  sym_pair = 28,
  sym__key = 29,
  sym__value = 30,
  sym_object = 31,
  sym_array = 32,
  sym_object_array = 33,
  sym_boolean = 34,
  aux_sym_document_repeat1 = 35,
  aux_sym_import_repeat1 = 36,
  aux_sym_block_array_repeat1 = 37,
  aux_sym_block_array_repeat2 = 38,
  aux_sym_array_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_AT] = "@",
  [anon_sym_delete] = "delete",
  [anon_sym_replace] = "replace",
  [anon_sym_import] = "import",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_multiline_string] = "multiline_string",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_overlay_operation] = "overlay_operation",
  [sym_import] = "import",
  [sym_block] = "block",
  [sym_block_array] = "block_array",
  [sym_block_array_item] = "block_array_item",
  [sym_scalar_array_field] = "scalar_array_field",
  [sym_pair] = "pair",
  [sym__key] = "_key",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_object_array] = "object_array",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_block_array_repeat1] = "block_array_repeat1",
  [aux_sym_block_array_repeat2] = "block_array_repeat2",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_delete] = anon_sym_delete,
  [anon_sym_replace] = anon_sym_replace,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_multiline_string] = sym_multiline_string,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_overlay_operation] = sym_overlay_operation,
  [sym_import] = sym_import,
  [sym_block] = sym_block,
  [sym_block_array] = sym_block_array,
  [sym_block_array_item] = sym_block_array_item,
  [sym_scalar_array_field] = sym_scalar_array_field,
  [sym_pair] = sym_pair,
  [sym__key] = sym__key,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_object_array] = sym_object_array,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_block_array_repeat1] = aux_sym_block_array_repeat1,
  [aux_sym_block_array_repeat2] = aux_sym_block_array_repeat2,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_delete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_replace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_overlay_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array_item] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_array_field] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_object_array] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_array_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_key, 2},
  [3] =
    {field_name, 0},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_key, 2},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(2);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_multiline_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_delete);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_replace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_delete] = ACTIONS(1),
    [anon_sym_replace] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_multiline_string] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(84),
    [sym__statement] = STATE(10),
    [sym_overlay_operation] = STATE(10),
    [sym_import] = STATE(10),
    [sym_block] = STATE(10),
    [sym_block_array] = STATE(10),
    [sym_scalar_array_field] = STATE(10),
    [sym_pair] = STATE(10),
    [sym__key] = STATE(54),
    [aux_sym_document_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_null,
    STATE(46), 1,
      sym_block_array_item,
    STATE(56), 1,
      aux_sym_block_array_repeat1,
    ACTIONS(21), 2,
      sym_multiline_string,
      sym_float,
    ACTIONS(23), 2,
      sym_string,
      sym_integer,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(65), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_object_array,
      sym_boolean,
  [41] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_null,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(49), 1,
      sym_block_array_item,
    STATE(58), 1,
      aux_sym_block_array_repeat1,
    ACTIONS(21), 2,
      sym_multiline_string,
      sym_float,
    ACTIONS(23), 2,
      sym_string,
      sym_integer,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(65), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_object_array,
      sym_boolean,
  [82] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(37), 2,
      sym_string,
      sym_integer,
    ACTIONS(35), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_object_array,
      sym_boolean,
  [115] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_import,
    ACTIONS(50), 1,
      sym_string,
    STATE(54), 1,
      sym__key,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(5), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [148] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(37), 2,
      sym_string,
      sym_integer,
    ACTIONS(35), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_object_array,
      sym_boolean,
  [181] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(5), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [213] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(37), 2,
      sym_string,
      sym_integer,
    ACTIONS(35), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_object_array,
      sym_boolean,
  [243] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(17), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [275] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(54), 1,
      sym__key,
    STATE(5), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [307] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(5), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [339] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(7), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [371] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(5), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [403] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(11), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [435] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 2,
      sym_string,
      sym_integer,
    ACTIONS(69), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(34), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_object_array,
      sym_boolean,
  [465] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(13), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [497] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      sym_string,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym__key,
    STATE(5), 8,
      sym__statement,
      sym_overlay_operation,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [529] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [545] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(81), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [561] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [577] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [593] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [625] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [641] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [657] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [673] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_string,
  [689] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [717] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [731] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [745] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(133), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [759] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [773] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [801] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(149), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [815] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [829] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(157), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [843] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(161), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [857] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(165), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [871] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(169), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(173), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_RBRACE,
      sym_string,
  [899] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    STATE(44), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [916] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(188), 1,
      sym_null,
    STATE(44), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [933] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    STATE(47), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [950] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(50), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [967] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    STATE(44), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [984] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    STATE(44), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [1001] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
    STATE(43), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [1018] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
    STATE(44), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [1035] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      sym_null,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
    STATE(48), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat2,
  [1052] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(203), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(207), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1076] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_LBRACK,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      anon_sym_COLON,
    STATE(39), 1,
      sym_array,
  [1092] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    ACTIONS(221), 2,
      anon_sym_LBRACE,
      sym_null,
  [1106] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 1,
      sym_null,
    STATE(51), 1,
      sym_block_array_item,
    STATE(61), 1,
      aux_sym_block_array_repeat1,
  [1122] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(221), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1134] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 1,
      sym_null,
    STATE(45), 1,
      sym_block_array_item,
    STATE(61), 1,
      aux_sym_block_array_repeat1,
  [1150] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    ACTIONS(232), 2,
      anon_sym_LBRACE,
      sym_null,
  [1164] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RBRACK,
    ACTIONS(203), 2,
      anon_sym_LBRACE,
      sym_null,
  [1178] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_LBRACE,
    ACTIONS(242), 1,
      sym_null,
    STATE(61), 1,
      aux_sym_block_array_repeat1,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1200] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      aux_sym_import_repeat1,
  [1213] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1222] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RBRACK,
    STATE(69), 1,
      aux_sym_array_repeat1,
  [1235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(30), 1,
      sym__key,
    ACTIONS(256), 2,
      sym_string,
      sym_identifier,
  [1255] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(232), 2,
      anon_sym_LBRACE,
      sym_null,
  [1266] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_array_repeat1,
  [1279] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      aux_sym_array_repeat1,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACK,
    STATE(73), 1,
      aux_sym_import_repeat1,
  [1305] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(79), 1,
      sym__key,
    ACTIONS(271), 2,
      sym_string,
      sym_identifier,
  [1316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      aux_sym_import_repeat1,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    ACTIONS(279), 1,
      sym_string,
  [1347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    ACTIONS(281), 1,
      sym_string,
  [1365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_string,
    ACTIONS(283), 1,
      anon_sym_RBRACK,
  [1375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym_object,
  [1385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_delete,
    ACTIONS(287), 1,
      anon_sym_replace,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      anon_sym_LBRACE,
      sym_null,
  [1403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_LBRACK,
    ACTIONS(291), 1,
      sym_string,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_string,
  [1420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 213,
  [SMALL_STATE(9)] = 243,
  [SMALL_STATE(10)] = 275,
  [SMALL_STATE(11)] = 307,
  [SMALL_STATE(12)] = 339,
  [SMALL_STATE(13)] = 371,
  [SMALL_STATE(14)] = 403,
  [SMALL_STATE(15)] = 435,
  [SMALL_STATE(16)] = 465,
  [SMALL_STATE(17)] = 497,
  [SMALL_STATE(18)] = 529,
  [SMALL_STATE(19)] = 545,
  [SMALL_STATE(20)] = 561,
  [SMALL_STATE(21)] = 577,
  [SMALL_STATE(22)] = 593,
  [SMALL_STATE(23)] = 609,
  [SMALL_STATE(24)] = 625,
  [SMALL_STATE(25)] = 641,
  [SMALL_STATE(26)] = 657,
  [SMALL_STATE(27)] = 673,
  [SMALL_STATE(28)] = 689,
  [SMALL_STATE(29)] = 703,
  [SMALL_STATE(30)] = 717,
  [SMALL_STATE(31)] = 731,
  [SMALL_STATE(32)] = 745,
  [SMALL_STATE(33)] = 759,
  [SMALL_STATE(34)] = 773,
  [SMALL_STATE(35)] = 787,
  [SMALL_STATE(36)] = 801,
  [SMALL_STATE(37)] = 815,
  [SMALL_STATE(38)] = 829,
  [SMALL_STATE(39)] = 843,
  [SMALL_STATE(40)] = 857,
  [SMALL_STATE(41)] = 871,
  [SMALL_STATE(42)] = 885,
  [SMALL_STATE(43)] = 899,
  [SMALL_STATE(44)] = 916,
  [SMALL_STATE(45)] = 933,
  [SMALL_STATE(46)] = 950,
  [SMALL_STATE(47)] = 967,
  [SMALL_STATE(48)] = 984,
  [SMALL_STATE(49)] = 1001,
  [SMALL_STATE(50)] = 1018,
  [SMALL_STATE(51)] = 1035,
  [SMALL_STATE(52)] = 1052,
  [SMALL_STATE(53)] = 1064,
  [SMALL_STATE(54)] = 1076,
  [SMALL_STATE(55)] = 1092,
  [SMALL_STATE(56)] = 1106,
  [SMALL_STATE(57)] = 1122,
  [SMALL_STATE(58)] = 1134,
  [SMALL_STATE(59)] = 1150,
  [SMALL_STATE(60)] = 1164,
  [SMALL_STATE(61)] = 1178,
  [SMALL_STATE(62)] = 1191,
  [SMALL_STATE(63)] = 1200,
  [SMALL_STATE(64)] = 1213,
  [SMALL_STATE(65)] = 1222,
  [SMALL_STATE(66)] = 1235,
  [SMALL_STATE(67)] = 1244,
  [SMALL_STATE(68)] = 1255,
  [SMALL_STATE(69)] = 1266,
  [SMALL_STATE(70)] = 1279,
  [SMALL_STATE(71)] = 1292,
  [SMALL_STATE(72)] = 1305,
  [SMALL_STATE(73)] = 1316,
  [SMALL_STATE(74)] = 1329,
  [SMALL_STATE(75)] = 1337,
  [SMALL_STATE(76)] = 1347,
  [SMALL_STATE(77)] = 1355,
  [SMALL_STATE(78)] = 1365,
  [SMALL_STATE(79)] = 1375,
  [SMALL_STATE(80)] = 1385,
  [SMALL_STATE(81)] = 1395,
  [SMALL_STATE(82)] = 1403,
  [SMALL_STATE(83)] = 1413,
  [SMALL_STATE(84)] = 1420,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(54),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(80),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(82),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(54),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_array, 5),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_array, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_array, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_array, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_array, 4),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_array, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 4, .production_id = 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 4, .production_id = 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overlay_operation, 3, .production_id = 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_overlay_operation, 3, .production_id = 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, .production_id = 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overlay_operation, 4, .production_id = 5),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_overlay_operation, 4, .production_id = 5),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 6, .production_id = 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 6, .production_id = 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 3),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, .production_id = 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 5, .production_id = 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 5, .production_id = 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 3, .production_id = 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 3, .production_id = 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat2, 2),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat2, 2), SHIFT_REPEAT(16),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat2, 2), SHIFT_REPEAT(53),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat2, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_object, 2), SHIFT(62),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block_array_item, 2), REDUCE(sym_object, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__value, 1), SHIFT(81),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 1),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_object, 3), SHIFT(64),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block_array_item, 3), REDUCE(sym_object, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2), SHIFT_REPEAT(68),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(83),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 4),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(8),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [293] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_skg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
