#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  sym_identifier = 1,
  anon_sym_import = 2,
  anon_sym_LBRACK = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COLON = 8,
  sym_multiline_string = 9,
  sym_string = 10,
  sym_float = 11,
  sym_integer = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_null = 15,
  sym_comment = 16,
  sym_document = 17,
  sym__statement = 18,
  sym_import = 19,
  sym_block = 20,
  sym_block_array = 21,
  sym_block_array_item = 22,
  sym_scalar_array_field = 23,
  sym_pair = 24,
  sym__key = 25,
  sym__value = 26,
  sym_object = 27,
  sym_array = 28,
  sym_boolean = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_import_repeat1 = 31,
  aux_sym_block_array_repeat1 = 32,
  aux_sym_array_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_import] = "import",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_multiline_string] = "multiline_string",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_import] = "import",
  [sym_block] = "block",
  [sym_block_array] = "block_array",
  [sym_block_array_item] = "block_array_item",
  [sym_scalar_array_field] = "scalar_array_field",
  [sym_pair] = "pair",
  [sym__key] = "_key",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_block_array_repeat1] = "block_array_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_multiline_string] = sym_multiline_string,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_import] = sym_import,
  [sym_block] = sym_block,
  [sym_block_array] = sym_block_array,
  [sym_block_array_item] = sym_block_array_item,
  [sym_scalar_array_field] = sym_scalar_array_field,
  [sym_pair] = sym_pair,
  [sym__key] = sym__key,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_block_array_repeat1] = aux_sym_block_array_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array_item] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_array_field] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 7,
  [9] = 4,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 16,
  [20] = 17,
  [21] = 14,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 38,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 40,
  [52] = 31,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 30,
  [58] = 33,
  [59] = 59,
  [60] = 44,
  [61] = 61,
  [62] = 45,
  [63] = 46,
  [64] = 64,
  [65] = 47,
  [66] = 48,
  [67] = 28,
  [68] = 64,
  [69] = 34,
  [70] = 59,
  [71] = 29,
  [72] = 32,
  [73] = 41,
  [74] = 43,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 79,
  [83] = 83,
  [84] = 84,
  [85] = 84,
  [86] = 86,
  [87] = 75,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 89,
  [94] = 94,
  [95] = 94,
  [96] = 88,
  [97] = 91,
  [98] = 98,
  [99] = 99,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(2);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_multiline_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 9},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 9},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 9},
  [89] = {.lex_state = 9},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 9},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 9},
  [94] = {.lex_state = 9},
  [95] = {.lex_state = 9},
  [96] = {.lex_state = 9},
  [97] = {.lex_state = 9},
  [98] = {.lex_state = 9},
  [99] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_multiline_string] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(99),
    [sym__statement] = STATE(27),
    [sym_import] = STATE(27),
    [sym_block] = STATE(27),
    [sym_block_array] = STATE(27),
    [sym_scalar_array_field] = STATE(27),
    [sym_pair] = STATE(27),
    [sym__key] = STATE(40),
    [aux_sym_document_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [sym_string] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_null,
    ACTIONS(19), 2,
      sym_multiline_string,
      sym_float,
    ACTIONS(21), 2,
      sym_string,
      sym_integer,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
    STATE(85), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_null,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      sym_multiline_string,
      sym_float,
    ACTIONS(31), 2,
      sym_string,
      sym_integer,
    STATE(37), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
    STATE(84), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [76] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 2,
      sym_string,
      sym_integer,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(19), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(85), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [108] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(41), 2,
      sym_string,
      sym_integer,
    ACTIONS(39), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(90), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [140] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(41), 2,
      sym_string,
      sym_integer,
    ACTIONS(39), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(90), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [172] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(41), 2,
      sym_string,
      sym_integer,
    ACTIONS(39), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(90), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [204] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(41), 2,
      sym_string,
      sym_integer,
    ACTIONS(39), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(90), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [236] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_string,
      sym_integer,
    ACTIONS(29), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(84), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [268] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 2,
      sym_string,
      sym_integer,
    ACTIONS(59), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(55), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(39), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [297] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 2,
      sym_string,
      sym_integer,
    ACTIONS(61), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(38), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [326] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(41), 2,
      sym_string,
      sym_integer,
    ACTIONS(39), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(90), 4,
      sym__value,
      sym_object,
      sym_array,
      sym_boolean,
  [355] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 1,
      sym_string,
    STATE(51), 1,
      sym__key,
    STATE(26), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [383] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_import,
    ACTIONS(81), 1,
      sym_string,
    STATE(40), 1,
      sym__key,
    STATE(14), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [411] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [439] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [467] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(22), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [495] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(15), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [523] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [551] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(23), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [579] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(99), 1,
      anon_sym_import,
    ACTIONS(102), 1,
      sym_string,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [607] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [635] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [663] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(19), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [691] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(16), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [719] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_import,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym__key,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [747] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      sym__key,
    STATE(14), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [817] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [831] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(133), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [859] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [873] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_RBRACK,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
    ACTIONS(150), 1,
      sym_null,
    STATE(35), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [890] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_null,
    STATE(35), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [907] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_null,
    ACTIONS(159), 1,
      anon_sym_RBRACK,
    STATE(35), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [924] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(163), 2,
      anon_sym_import,
      sym_identifier,
  [936] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(163), 2,
      anon_sym_import,
      sym_identifier,
  [948] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_LBRACK,
    ACTIONS(167), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      anon_sym_COLON,
    STATE(46), 1,
      sym_array,
  [964] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(173), 2,
      anon_sym_import,
      sym_identifier,
  [976] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(177), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [988] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(181), 2,
      anon_sym_import,
      sym_identifier,
  [1000] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(185), 2,
      anon_sym_import,
      sym_identifier,
  [1012] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(189), 2,
      anon_sym_import,
      sym_identifier,
  [1024] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(193), 2,
      anon_sym_import,
      sym_identifier,
  [1036] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(197), 2,
      anon_sym_import,
      sym_identifier,
  [1048] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(201), 2,
      anon_sym_import,
      sym_identifier,
  [1060] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
    ACTIONS(209), 2,
      anon_sym_LBRACE,
      sym_null,
  [1074] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    ACTIONS(177), 2,
      anon_sym_LBRACE,
      sym_null,
  [1088] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_LBRACK,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      anon_sym_COLON,
    STATE(63), 1,
      sym_array,
  [1104] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(131), 2,
      anon_sym_import,
      sym_identifier,
  [1116] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    ACTIONS(225), 2,
      anon_sym_LBRACE,
      sym_null,
  [1142] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(235), 2,
      anon_sym_RBRACE,
      sym_string,
  [1154] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(235), 2,
      ts_builtin_sym_end,
      sym_string,
  [1166] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(127), 2,
      anon_sym_import,
      sym_identifier,
  [1178] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(139), 2,
      anon_sym_import,
      sym_identifier,
  [1190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(239), 2,
      anon_sym_import,
      sym_identifier,
  [1202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(185), 2,
      anon_sym_import,
      sym_identifier,
  [1214] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    ACTIONS(209), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1226] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(189), 2,
      anon_sym_import,
      sym_identifier,
  [1238] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(193), 2,
      anon_sym_import,
      sym_identifier,
  [1250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(245), 2,
      anon_sym_import,
      sym_identifier,
  [1262] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(197), 2,
      anon_sym_import,
      sym_identifier,
  [1274] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(201), 2,
      anon_sym_import,
      sym_identifier,
  [1286] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(119), 2,
      anon_sym_import,
      sym_identifier,
  [1298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(245), 2,
      anon_sym_import,
      sym_identifier,
  [1310] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(143), 2,
      anon_sym_import,
      sym_identifier,
  [1322] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(239), 2,
      anon_sym_import,
      sym_identifier,
  [1334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(123), 2,
      anon_sym_import,
      sym_identifier,
  [1346] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(135), 2,
      anon_sym_import,
      sym_identifier,
  [1358] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(173), 2,
      anon_sym_import,
      sym_identifier,
  [1370] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(181), 2,
      anon_sym_import,
      sym_identifier,
  [1382] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      aux_sym_import_repeat1,
  [1395] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_array_repeat1,
  [1408] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1417] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_array_repeat1,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
    STATE(83), 1,
      aux_sym_import_repeat1,
  [1443] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
    STATE(80), 1,
      aux_sym_array_repeat1,
  [1456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1465] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RBRACK,
    STATE(83), 1,
      aux_sym_import_repeat1,
  [1478] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
    STATE(83), 1,
      aux_sym_import_repeat1,
  [1491] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_array_repeat1,
  [1504] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      aux_sym_array_repeat1,
  [1517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 3,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_null,
  [1526] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      aux_sym_import_repeat1,
  [1539] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LBRACK,
    ACTIONS(289), 1,
      sym_string,
  [1549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
    ACTIONS(291), 1,
      sym_string,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1567] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_string,
    ACTIONS(293), 1,
      anon_sym_RBRACK,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1585] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RBRACK,
    ACTIONS(291), 1,
      sym_string,
  [1595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_RBRACK,
    ACTIONS(297), 1,
      sym_string,
  [1605] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_RBRACK,
    ACTIONS(301), 1,
      sym_string,
  [1615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_LBRACK,
    ACTIONS(305), 1,
      sym_string,
  [1625] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_string,
    ACTIONS(307), 1,
      anon_sym_RBRACK,
  [1635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_string,
  [1642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 172,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 236,
  [SMALL_STATE(10)] = 268,
  [SMALL_STATE(11)] = 297,
  [SMALL_STATE(12)] = 326,
  [SMALL_STATE(13)] = 355,
  [SMALL_STATE(14)] = 383,
  [SMALL_STATE(15)] = 411,
  [SMALL_STATE(16)] = 439,
  [SMALL_STATE(17)] = 467,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 523,
  [SMALL_STATE(20)] = 551,
  [SMALL_STATE(21)] = 579,
  [SMALL_STATE(22)] = 607,
  [SMALL_STATE(23)] = 635,
  [SMALL_STATE(24)] = 663,
  [SMALL_STATE(25)] = 691,
  [SMALL_STATE(26)] = 719,
  [SMALL_STATE(27)] = 747,
  [SMALL_STATE(28)] = 775,
  [SMALL_STATE(29)] = 789,
  [SMALL_STATE(30)] = 803,
  [SMALL_STATE(31)] = 817,
  [SMALL_STATE(32)] = 831,
  [SMALL_STATE(33)] = 845,
  [SMALL_STATE(34)] = 859,
  [SMALL_STATE(35)] = 873,
  [SMALL_STATE(36)] = 890,
  [SMALL_STATE(37)] = 907,
  [SMALL_STATE(38)] = 924,
  [SMALL_STATE(39)] = 936,
  [SMALL_STATE(40)] = 948,
  [SMALL_STATE(41)] = 964,
  [SMALL_STATE(42)] = 976,
  [SMALL_STATE(43)] = 988,
  [SMALL_STATE(44)] = 1000,
  [SMALL_STATE(45)] = 1012,
  [SMALL_STATE(46)] = 1024,
  [SMALL_STATE(47)] = 1036,
  [SMALL_STATE(48)] = 1048,
  [SMALL_STATE(49)] = 1060,
  [SMALL_STATE(50)] = 1074,
  [SMALL_STATE(51)] = 1088,
  [SMALL_STATE(52)] = 1104,
  [SMALL_STATE(53)] = 1116,
  [SMALL_STATE(54)] = 1128,
  [SMALL_STATE(55)] = 1142,
  [SMALL_STATE(56)] = 1154,
  [SMALL_STATE(57)] = 1166,
  [SMALL_STATE(58)] = 1178,
  [SMALL_STATE(59)] = 1190,
  [SMALL_STATE(60)] = 1202,
  [SMALL_STATE(61)] = 1214,
  [SMALL_STATE(62)] = 1226,
  [SMALL_STATE(63)] = 1238,
  [SMALL_STATE(64)] = 1250,
  [SMALL_STATE(65)] = 1262,
  [SMALL_STATE(66)] = 1274,
  [SMALL_STATE(67)] = 1286,
  [SMALL_STATE(68)] = 1298,
  [SMALL_STATE(69)] = 1310,
  [SMALL_STATE(70)] = 1322,
  [SMALL_STATE(71)] = 1334,
  [SMALL_STATE(72)] = 1346,
  [SMALL_STATE(73)] = 1358,
  [SMALL_STATE(74)] = 1370,
  [SMALL_STATE(75)] = 1382,
  [SMALL_STATE(76)] = 1395,
  [SMALL_STATE(77)] = 1408,
  [SMALL_STATE(78)] = 1417,
  [SMALL_STATE(79)] = 1430,
  [SMALL_STATE(80)] = 1443,
  [SMALL_STATE(81)] = 1456,
  [SMALL_STATE(82)] = 1465,
  [SMALL_STATE(83)] = 1478,
  [SMALL_STATE(84)] = 1491,
  [SMALL_STATE(85)] = 1504,
  [SMALL_STATE(86)] = 1517,
  [SMALL_STATE(87)] = 1526,
  [SMALL_STATE(88)] = 1539,
  [SMALL_STATE(89)] = 1549,
  [SMALL_STATE(90)] = 1559,
  [SMALL_STATE(91)] = 1567,
  [SMALL_STATE(92)] = 1577,
  [SMALL_STATE(93)] = 1585,
  [SMALL_STATE(94)] = 1595,
  [SMALL_STATE(95)] = 1605,
  [SMALL_STATE(96)] = 1615,
  [SMALL_STATE(97)] = 1625,
  [SMALL_STATE(98)] = 1635,
  [SMALL_STATE(99)] = 1642,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(96),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(51),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(88),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(51),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2), SHIFT_REPEAT(13),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2), SHIFT_REPEAT(42),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 3),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, .production_id = 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 4, .production_id = 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 4, .production_id = 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 2),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, .production_id = 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 3, .production_id = 2),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 3, .production_id = 2),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_object, 3), SHIFT(77),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block_array_item, 3), REDUCE(sym_object, 3),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 3),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__value, 1), SHIFT(81),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__value, 1), REDUCE(aux_sym_block_array_repeat1, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 2),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_object, 2), SHIFT(86),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block_array_item, 2), REDUCE(sym_object, 2),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 2),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 2),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 4),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(12),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [270] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(98),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_skg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
