#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  sym_identifier = 1,
  anon_sym_import = 2,
  anon_sym_LBRACK = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COLON = 8,
  sym_multiline_string = 9,
  sym_string = 10,
  sym_float = 11,
  sym_integer = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_null = 15,
  sym_comment = 16,
  sym_document = 17,
  sym__statement = 18,
  sym_import = 19,
  sym_block = 20,
  sym_block_array = 21,
  sym_block_array_item = 22,
  sym_scalar_array_field = 23,
  sym_pair = 24,
  sym__key = 25,
  sym__value = 26,
  sym_array = 27,
  sym_boolean = 28,
  aux_sym_document_repeat1 = 29,
  aux_sym_import_repeat1 = 30,
  aux_sym_block_array_repeat1 = 31,
  aux_sym_array_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_import] = "import",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_multiline_string] = "multiline_string",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_import] = "import",
  [sym_block] = "block",
  [sym_block_array] = "block_array",
  [sym_block_array_item] = "block_array_item",
  [sym_scalar_array_field] = "scalar_array_field",
  [sym_pair] = "pair",
  [sym__key] = "_key",
  [sym__value] = "_value",
  [sym_array] = "array",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_block_array_repeat1] = "block_array_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_multiline_string] = sym_multiline_string,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_import] = sym_import,
  [sym_block] = sym_block,
  [sym_block_array] = sym_block_array,
  [sym_block_array_item] = sym_block_array_item,
  [sym_scalar_array_field] = sym_scalar_array_field,
  [sym_pair] = sym_pair,
  [sym__key] = sym__key,
  [sym__value] = sym__value,
  [sym_array] = sym_array,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_block_array_repeat1] = aux_sym_block_array_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array_item] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_array_field] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 5,
  [14] = 7,
  [15] = 6,
  [16] = 4,
  [17] = 17,
  [18] = 8,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 27,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 29,
  [41] = 22,
  [42] = 30,
  [43] = 24,
  [44] = 37,
  [45] = 45,
  [46] = 28,
  [47] = 34,
  [48] = 26,
  [49] = 49,
  [50] = 31,
  [51] = 32,
  [52] = 33,
  [53] = 25,
  [54] = 38,
  [55] = 45,
  [56] = 23,
  [57] = 49,
  [58] = 39,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 66,
  [67] = 67,
  [68] = 61,
  [69] = 62,
  [70] = 59,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 75,
  [79] = 72,
  [80] = 80,
  [81] = 77,
  [82] = 71,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(2);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_multiline_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 9},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_multiline_string] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(84),
    [sym__statement] = STATE(10),
    [sym_import] = STATE(10),
    [sym_block] = STATE(10),
    [sym_block_array] = STATE(10),
    [sym_scalar_array_field] = STATE(10),
    [sym_pair] = STATE(10),
    [sym__key] = STATE(29),
    [aux_sym_document_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [sym_string] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 2,
      sym_string,
      sym_integer,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
    ACTIONS(19), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(61), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [35] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      sym_string,
      sym_integer,
    STATE(31), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
    ACTIONS(27), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(68), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [70] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(36), 1,
      anon_sym_import,
    ACTIONS(39), 1,
      sym_string,
    STATE(29), 1,
      sym__key,
    STATE(4), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [98] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      sym_string,
    STATE(40), 1,
      sym__key,
    STATE(16), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [126] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(50), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      sym_string,
      sym_integer,
    ACTIONS(27), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(68), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [154] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(56), 2,
      sym_string,
      sym_integer,
    ACTIONS(54), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(80), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [182] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(56), 2,
      sym_string,
      sym_integer,
    ACTIONS(54), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(80), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [210] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(48), 1,
      sym_string,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym__key,
    STATE(5), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [238] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym__key,
    STATE(4), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [266] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(48), 1,
      sym_string,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym__key,
    STATE(13), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [294] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(48), 1,
      sym_string,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym__key,
    STATE(16), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [322] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(48), 1,
      sym_string,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym__key,
    STATE(16), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [350] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(56), 2,
      sym_string,
      sym_integer,
    ACTIONS(54), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(80), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [378] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      sym_string,
      sym_integer,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(19), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(61), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [406] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(77), 1,
      anon_sym_import,
    ACTIONS(80), 1,
      sym_string,
    STATE(40), 1,
      sym__key,
    STATE(16), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [434] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(48), 1,
      sym_string,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym__key,
    STATE(12), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [462] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(56), 2,
      sym_string,
      sym_integer,
    ACTIONS(54), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(80), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [490] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(89), 2,
      sym_string,
      sym_integer,
    ACTIONS(87), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(39), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [515] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(56), 2,
      sym_string,
      sym_integer,
    ACTIONS(54), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(80), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [540] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 2,
      sym_string,
      sym_integer,
    ACTIONS(97), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(93), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(58), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [565] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(99), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [593] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(107), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [607] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(111), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [621] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_string,
  [635] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(121), 2,
      anon_sym_RBRACE,
      sym_string,
  [647] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      sym_string,
  [659] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_COLON,
    STATE(33), 1,
      sym_array,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(135), 2,
      anon_sym_import,
      sym_identifier,
  [687] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    STATE(35), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [701] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(141), 2,
      anon_sym_import,
      sym_identifier,
  [713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(145), 2,
      anon_sym_import,
      sym_identifier,
  [725] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(149), 2,
      anon_sym_import,
      sym_identifier,
  [737] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
    ACTIONS(153), 1,
      anon_sym_LBRACE,
    STATE(35), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [751] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_string,
  [763] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(158), 2,
      anon_sym_import,
      sym_identifier,
  [775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(162), 2,
      anon_sym_import,
      sym_identifier,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(166), 2,
      anon_sym_import,
      sym_identifier,
  [799] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LBRACK,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(172), 1,
      anon_sym_COLON,
    STATE(52), 1,
      sym_array,
  [815] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(101), 2,
      anon_sym_import,
      sym_identifier,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(135), 2,
      anon_sym_import,
      sym_identifier,
  [839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(109), 2,
      anon_sym_import,
      sym_identifier,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(158), 2,
      anon_sym_import,
      sym_identifier,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(176), 2,
      anon_sym_import,
      sym_identifier,
  [875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_string,
  [887] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(149), 2,
      anon_sym_import,
      sym_identifier,
  [899] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(117), 2,
      anon_sym_import,
      sym_identifier,
  [911] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      sym_string,
    ACTIONS(180), 2,
      anon_sym_import,
      sym_identifier,
  [923] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    STATE(35), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [937] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(141), 2,
      anon_sym_import,
      sym_identifier,
  [949] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(145), 2,
      anon_sym_import,
      sym_identifier,
  [961] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(113), 2,
      anon_sym_import,
      sym_identifier,
  [973] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(162), 2,
      anon_sym_import,
      sym_identifier,
  [985] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(176), 2,
      anon_sym_import,
      sym_identifier,
  [997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(105), 2,
      anon_sym_import,
      sym_identifier,
  [1009] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(180), 2,
      anon_sym_import,
      sym_identifier,
  [1021] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(166), 2,
      anon_sym_import,
      sym_identifier,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      aux_sym_import_repeat1,
  [1046] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      aux_sym_import_repeat1,
  [1059] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    STATE(69), 1,
      aux_sym_array_repeat1,
  [1072] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_array_repeat1,
  [1085] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      aux_sym_import_repeat1,
  [1098] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
    STATE(64), 1,
      aux_sym_array_repeat1,
  [1111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      aux_sym_import_repeat1,
  [1124] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(214), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1135] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1146] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      aux_sym_array_repeat1,
  [1159] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_RBRACK,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_array_repeat1,
  [1172] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      aux_sym_import_repeat1,
  [1185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    ACTIONS(232), 1,
      sym_string,
  [1195] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    ACTIONS(232), 1,
      sym_string,
  [1205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1213] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1221] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_RBRACK,
    ACTIONS(238), 1,
      sym_string,
  [1231] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1239] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      sym_string,
  [1249] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
    ACTIONS(246), 1,
      sym_string,
  [1259] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    ACTIONS(232), 1,
      sym_string,
  [1269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1277] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LBRACK,
    ACTIONS(250), 1,
      sym_string,
  [1287] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_string,
    ACTIONS(252), 1,
      anon_sym_RBRACK,
  [1297] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_string,
  [1304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 98,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 266,
  [SMALL_STATE(12)] = 294,
  [SMALL_STATE(13)] = 322,
  [SMALL_STATE(14)] = 350,
  [SMALL_STATE(15)] = 378,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 434,
  [SMALL_STATE(18)] = 462,
  [SMALL_STATE(19)] = 490,
  [SMALL_STATE(20)] = 515,
  [SMALL_STATE(21)] = 540,
  [SMALL_STATE(22)] = 565,
  [SMALL_STATE(23)] = 579,
  [SMALL_STATE(24)] = 593,
  [SMALL_STATE(25)] = 607,
  [SMALL_STATE(26)] = 621,
  [SMALL_STATE(27)] = 635,
  [SMALL_STATE(28)] = 647,
  [SMALL_STATE(29)] = 659,
  [SMALL_STATE(30)] = 675,
  [SMALL_STATE(31)] = 687,
  [SMALL_STATE(32)] = 701,
  [SMALL_STATE(33)] = 713,
  [SMALL_STATE(34)] = 725,
  [SMALL_STATE(35)] = 737,
  [SMALL_STATE(36)] = 751,
  [SMALL_STATE(37)] = 763,
  [SMALL_STATE(38)] = 775,
  [SMALL_STATE(39)] = 787,
  [SMALL_STATE(40)] = 799,
  [SMALL_STATE(41)] = 815,
  [SMALL_STATE(42)] = 827,
  [SMALL_STATE(43)] = 839,
  [SMALL_STATE(44)] = 851,
  [SMALL_STATE(45)] = 863,
  [SMALL_STATE(46)] = 875,
  [SMALL_STATE(47)] = 887,
  [SMALL_STATE(48)] = 899,
  [SMALL_STATE(49)] = 911,
  [SMALL_STATE(50)] = 923,
  [SMALL_STATE(51)] = 937,
  [SMALL_STATE(52)] = 949,
  [SMALL_STATE(53)] = 961,
  [SMALL_STATE(54)] = 973,
  [SMALL_STATE(55)] = 985,
  [SMALL_STATE(56)] = 997,
  [SMALL_STATE(57)] = 1009,
  [SMALL_STATE(58)] = 1021,
  [SMALL_STATE(59)] = 1033,
  [SMALL_STATE(60)] = 1046,
  [SMALL_STATE(61)] = 1059,
  [SMALL_STATE(62)] = 1072,
  [SMALL_STATE(63)] = 1085,
  [SMALL_STATE(64)] = 1098,
  [SMALL_STATE(65)] = 1111,
  [SMALL_STATE(66)] = 1124,
  [SMALL_STATE(67)] = 1135,
  [SMALL_STATE(68)] = 1146,
  [SMALL_STATE(69)] = 1159,
  [SMALL_STATE(70)] = 1172,
  [SMALL_STATE(71)] = 1185,
  [SMALL_STATE(72)] = 1195,
  [SMALL_STATE(73)] = 1205,
  [SMALL_STATE(74)] = 1213,
  [SMALL_STATE(75)] = 1221,
  [SMALL_STATE(76)] = 1231,
  [SMALL_STATE(77)] = 1239,
  [SMALL_STATE(78)] = 1249,
  [SMALL_STATE(79)] = 1259,
  [SMALL_STATE(80)] = 1269,
  [SMALL_STATE(81)] = 1277,
  [SMALL_STATE(82)] = 1287,
  [SMALL_STATE(83)] = 1297,
  [SMALL_STATE(84)] = 1304,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(81),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(77),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, .production_id = 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 4, .production_id = 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 4, .production_id = 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2), SHIFT_REPEAT(17),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, .production_id = 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 3, .production_id = 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 3, .production_id = 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(83),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(20),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 4),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [254] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_skg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
