name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    uses: tenebrux/github-workflows/.github/workflows/zig-ci.yml@master
    with:
      zig-fmt-paths: "zig/"
